feat: add canonical handling
gitcoinco/grants-stack-indexer pull request #428
Opened 2024-02-14 07:15 UTC by thelostone-mc

Fixes https://github.com/gitcoinco/grants-stack-indexer/issues/427

2024-02-14 07:28 UTC, thelostone-mc commented on src/indexer/allo/v2/handleEvent.ts
> +  // TODO: fetch the canonical project from the database
Do we have an example I can use as a reference ?

2024-02-16 13:18 UTC, gravityblast commented on src/indexer/allo/v2/handleEvent.ts
> +    }
I suggest not to throw an error here. The project might not exist yet if the other chain is slower to index

2024-02-16 13:20 UTC, gravityblast commented on src/indexer/allo/v2/handleEvent.ts
> +    }
I would rather set the `type` based on the metadata without checking the db

2024-02-16 14:02 UTC, boudra requested changes
I noticed some castings and some issues that will be errors for the linter
I want to suggest this as a more robust way to do the classification (i didn't try the code so it might need modification):

```ts
const linkedProjectMetadata = z.object({
    "canonical": z.object({
           chainId: z.number(),
           registryAddress: z.string()
    })
});

if(linkedProjectMetadata.safeParse(metadata).success) {
   return "linked"
}

return "canonical";
}
```
without the CanonicalProject type.

this way we can start validating the metadatas

2024-02-19 08:22 UTC, thelostone-mc commented on src/indexer/allo/v2/handleEvent.ts
> +      chainId: z.string(),
```suggestion
      chainId: z.number(),
```

2024-02-19 14:41 UTC, boudra approved these changes
⚠️ before you merge please increase the schema version or the schema changes won't be applied: https://github.com/gitcoinco/grants-stack-indexer?tab=readme-ov-file#deployment ⚠️

2024-02-19 15:32 UTC, merged