Support Direct Grants
gitcoinco/grants-stack-indexer pull request #451
Opened 2024-02-16 14:15 UTC by 0xKurt

2024-02-26 10:08 UTC, boudra requested changes

2024-02-26 10:08 UTC, boudra commented on src/indexer/allo/v2/handleEvent.ts
> +        default:
we should throw an error if the strategy is not recognized instead of doing something that might not make sense and cause other problems

2024-02-26 10:08 UTC, boudra commented on src/indexer/allo/v2/handleEvent.ts
> +      let applicationsStartTime: Date | null = new Date();
it be less error prone if the initial values were null, not sure if there's ever a time that we want to set these dates to the current dates

2024-02-26 10:08 UTC, boudra commented on src/indexer/allo/v2/handleEvent.ts
>          applicationsStartTime: isNaN(applicationsStartTime.getTime())
applicationsStartTime could be null, it's not checked like the other ones

2024-02-26 10:08 UTC, boudra commented on src/indexer/allo/v2/handleEvent.ts
> +        // todo: update for Andrea's changes
what needs to be updated?

2024-02-26 10:08 UTC, boudra commented on src/config.ts
> +const CHAIN_DATA_VERSION = "33";
i think you need to increase this further

2024-02-27 08:27 UTC, thelostone-mc approved these changes

2024-02-27 11:29 UTC, boudra approved these changes

2024-02-27 11:49 UTC, merged